---
global:
  functionTemplates:
    - templates/parts/volumes.tpl
    - templates/parts/networks.tpl
    - templates/parts/extra_containers.tpl
jobs:
  - name: du-workload
    jobIterations: 1
    qps: 4
    burst: 4
    namespacedIterations: false
    namespace: "workload"
    podWait: false
    cleanup: true
    waitWhenFinished: true
    maxWaitTimeout: 5m
    errorOnVerify: true
    defaultMissingKeysWithZero: true
    objects:
    # Templates
      # Template of Gu Pods with fedora-stress-ng
      - objectTemplate: templates/common/configmap.yaml
        replicas: 2
        inputVars:
          group: "guaranteed"
      - objectTemplate: templates/common/secret.yaml
        replicas: 4
        inputVars:
          group: "guaranteed"
      - objectTemplate: templates/guaranteed/deployment.yaml
        replicas: 1
        inputVars:
          {{- if eq (index $ "REGISTRY") nil }}
          Image_stressng: 'quay.io/rh_ee_apalanis/fedora-stress-ng'
          Image_nginx: 'quay.io/rh_ee_apalanis/sampleapp'
          {{- else }}
          Image_stressng: '{{ .REGISTRY }}/fedora-stress-ng'
          Image_nginx: '{{ .REGISTRY }}/sampleapp'
          {{- end }}
          volumes:
            - value: configmap-guaranteed-1
              type: configMap
              path: /var/configmap1
            - value: configmap-guaranteed-2
              type: configMap
              path: /var/configmap2
            - value: secret-guaranteed-1
              type: secret
              path: /var/secret1
            - value: secret-guaranteed-2
              type: secret
              path: /var/secret2
            - value: secret-guaranteed-3
              type: secret
              path: /var/secret3
            - value: secret-guaranteed-4
              type: secret
              path: /var/secret4

      - objectTemplate: templates/guaranteed/service.yaml
        replicas: 1

      - objectTemplate: templates/common/configmap.yaml
        replicas: 2
      - objectTemplate: templates/common/secret.yaml
        replicas: 4

      # Template of burstable pods with exec probes
      - objectTemplate: templates/webserver/webserver-deployment.yaml
        replicas: 4
        inputVars:
          {{- if eq (index $ "REGISTRY") nil }}
          Image_stressng: 'quay.io/rh_ee_apalanis/fedora-stress-ng'
          Image_nginx: 'quay.io/rh_ee_apalanis/sampleapp'
          {{- else }}
          Image_stressng: '{{ .REGISTRY }}/fedora-stress-ng'
          Image_nginx: '{{ .REGISTRY }}/sampleapp'
          {{- end }}
          volumes:
            - value: configmap-1
              type: configMap
              path: /var/configmap1
            - value: configmap-2
              type: configMap
              path: /var/configmap2
            - value: secret-1
              type: secret
              path: /var/secret1
            - value: secret-2
              type: secret
              path: /var/secret2
            - value: secret-3
              type: secret
              path: /var/secret3
            - value: secret-4
              type: secret
              path: /var/secret4
      - objectTemplate: templates/webserver/webserver-service.yaml
        replicas: 4
      - objectTemplate: templates/webserver/curl-deployment.yaml
        replicas: 4
        inputVars:
          {{- if eq (index $ "REGISTRY") nil }}
          Image_nginx: 'quay.io/rh_ee_apalanis/sampleapp'
          Image_curl: 'quay.io/rh_ee_apalanis/curl'
          {{- else }}
          Image_nginx: '{{ .REGISTRY }}/sampleapp'
          Image_curl: '{{ .REGISTRY }}/curl'
          {{- end }}
          volumes:
            - value: configmap-1
              type: configMap
              path: /var/configmap1
            - value: configmap-2
              type: configMap
              path: /var/configmap2
            - value: secret-1
              type: secret
              path: /var/secret1
            - value: secret-2
              type: secret
              path: /var/secret2
            - value: secret-3
              type: secret
              path: /var/secret3
            - value: secret-4
              type: secret
              path: /var/secret4

      # Templates of burstable pods with kubeapiserver reqs
      - objectTemplate: templates/kubectlapp/serviceaccount.yaml
        replicas: 6
      - objectTemplate: templates/kubectlapp/role.yaml
        replicas: 6
      - objectTemplate: templates/kubectlapp/rolebinding.yaml
        replicas: 6
      - objectTemplate: templates/kubectlapp/deployment.yaml
        replicas: 6
        inputVars:
          {{- if eq (index $ "REGISTRY") nil }}
          Image_nginx: 'quay.io/rh_ee_apalanis/sampleapp'
          Image_kubectl: 'quay.io/rh_ee_apalanis/kubectl'
          {{- else }}
          Image_nginx: '{{ .REGISTRY }}/sampleapp'
          Image_kubectl: '{{ .REGISTRY }}/kubectl'
          {{- end }}
          volumes:
            - value: configmap-1
              type: configMap
              path: /var/configmap1
            - value: configmap-2
              type: configMap
              path: /var/configmap2
            - value: secret-1
              type: secret
              path: /var/secret1
            - value: secret-2
              type: secret
              path: /var/secret2
            - value: secret-3
              type: secret
              path: /var/secret3
            - value: secret-4
              type: secret
              path: /var/secret4

      # Template with storage stress on PVC claims
      - objectTemplate: templates/common/pv.yaml
        replicas: 1
        inputVars:
          storage_class: standard
          size: 1Gi
          group: storageio
      - objectTemplate: templates/common/pvc.yaml
        replicas: 1
        inputVars:
          storage_class: standard
          size: 1Gi
          group: storageio
      - objectTemplate: templates/storageio/deployment.yaml
        replicas: 1
        inputVars:
          group: storageio
          {{- if eq (index $ "REGISTRY") nil }}
          Image_stressng: 'quay.io/rh_ee_apalanis/fedora-stress-ng'
          Image_nginx: 'quay.io/rh_ee_apalanis/sampleapp'
          {{- else }}
          Image_stressng: '{{ .REGISTRY }}/fedora-stress-ng'
          Image_nginx: '{{ .REGISTRY }}/sampleapp'
          {{- end }}