---
global:
  functionTemplates:
    - templates/common/volumes.tpl
jobs:
  - name: du-workload
    jobIterations: 1
    qps: 4
    burst: 4
    namespacedIterations: false
    namespace: "workload"
    podWait: false
    cleanup: true
    waitWhenFinished: true
    maxWaitTimeout: 5m
    errorOnVerify: true
    defaultMissingKeysWithZero: true
    objects:
    # Templates
      # Template of Gu Pods with fedora-stress-ng
      - objectTemplate: templates/guaranteed/service.yaml
        replicas: 1
      - objectTemplate: templates/common/configmap.yaml
        replicas: 2
        inputVars:
          group: "guaranteed"
      - objectTemplate: templates/common/secret.yaml
        replicas: 4
        inputVars:
          group: "guaranteed"
      - objectTemplate: templates/guaranteed/deployment.yaml
        replicas: 1
        inputVars:
          Image_stressng: '{{ or .REGISTRY "quay.io/rh_ee_apalanis" }}/fedora-stress-ng'
          Image_nginx: '{{ or .REGISTRY "quay.io/rh_ee_apalanis" }}/sampleapp'
          volumes:
            - name: configmap-guaranteed-1
              type: configMap
              path: /var/configmap1
            - name: configmap-guaranteed-2
              type: configMap
              path: /var/configmap2
            - name: secret-guaranteed-1
              type: secret
              path: /var/secret1
            - name: secret-guaranteed-2
              type: secret
              path: /var/secret2
            - name: secret-guaranteed-3
              type: secret
              path: /var/secret3
            - name: secret-guaranteed-4
              type: secret
              path: /var/secret4

      - objectTemplate: templates/common/configmap.yaml
        replicas: 2
      - objectTemplate: templates/common/secret.yaml
        replicas: 4

      # Template of burstable pods with exec probes
      - objectTemplate: templates/webserver/webserver-deployment.yaml
        replicas: 4
        inputVars:
          Image_stressng: '{{ or .REGISTRY "quay.io/rh_ee_apalanis" }}/fedora-stress-ng'
          Image_nginx: '{{ or .REGISTRY "quay.io/rh_ee_apalanis" }}/sampleapp'
          volumes:
            - name: configmap-1
              type: configMap
              path: /var/configmap1
            - name: configmap-2
              type: configMap
              path: /var/configmap2
            - name: secret-1
              type: secret
              path: /var/secret1
            - name: secret-2
              type: secret
              path: /var/secret2
            - name: secret-3
              type: secret
              path: /var/secret3
            - name: secret-4
              type: secret
              path: /var/secret4
      - objectTemplate: templates/webserver/webserver-service.yaml
        replicas: 4
      - objectTemplate: templates/webserver/curl-deployment.yaml
        replicas: 4
        inputVars:
          Image_nginx: '{{ or .REGISTRY "quay.io/rh_ee_apalanis" }}/sampleapp'
          Image_curl: '{{ or .REGISTRY "quay.io/rh_ee_apalanis" }}/curl'
          volumes:
            - name: configmap-1
              type: configMap
              path: /var/configmap1
            - name: configmap-2
              type: configMap
              path: /var/configmap2
            - name: secret-1
              type: secret
              path: /var/secret1
            - name: secret-2
              type: secret
              path: /var/secret2
            - name: secret-3
              type: secret
              path: /var/secret3
            - name: secret-4
              type: secret
              path: /var/secret4

      # Templates of burstable pods with kubeapiserver reqs
      - objectTemplate: templates/kubectlapp/serviceaccount.yaml
        replicas: 6
      - objectTemplate: templates/kubectlapp/role.yaml
        replicas: 6
      - objectTemplate: templates/kubectlapp/rolebinding.yaml
        replicas: 6
      - objectTemplate: templates/kubectlapp/deployment.yaml
        replicas: 6
        inputVars:
          Image_nginx: '{{ or .REGISTRY "quay.io/rh_ee_apalanis" }}/sampleapp'
          Image_kubectl: '{{ or .REGISTRY "quay.io/rh_ee_apalanis" }}/kubectl'
          volumes:
            - name: configmap-1
              type: configMap
              path: /var/configmap1
            - name: configmap-2
              type: configMap
              path: /var/configmap2
            - name: secret-1
              type: secret
              path: /var/secret1
            - name: secret-2
              type: secret
              path: /var/secret2
            - name: secret-3
              type: secret
              path: /var/secret3
            - name: secret-4
              type: secret
              path: /var/secret4

      {{- if .ENABLE_PTP }}
      # Template with ptp events consumer
      - objectTemplate: templates/ptp-events-consumer/service-account.yaml
        replicas: 1
      - objectTemplate: templates/ptp-events-consumer/deployment.yaml
        replicas: 1
        inputVars:
          Image_ptp_consumer: '{{ or .REGISTRY "quay.io/jenchen" }}/ptp-event-consumer'
          short_node_name: '{{ (split "." .NODE_NAME)._0 }}'
      - objectTemplate: templates/ptp-events-consumer/service.yaml
        replicas: 1
      {{- end }}

      # Template with storage stress on PVC claims
      - objectTemplate: templates/common/pv.yaml
        replicas: 1
        inputVars:
          storage_class: standard
          size: 1Gi
          group: storageio
      - objectTemplate: templates/common/pvc.yaml
        replicas: 1
        inputVars:
          storage_class: standard
          size: 1Gi
          group: storageio
      - objectTemplate: templates/storageio/deployment.yaml
        replicas: 1
        inputVars:
          Image_stressng: '{{ or .REGISTRY "quay.io/rh_ee_apalanis" }}/fedora-stress-ng'
          Image_nginx: '{{ or .REGISTRY "quay.io/rh_ee_apalanis" }}/sampleapp'
          group: storageio


      - objectTemplate: templates/common/pvc.yaml
        replicas: 1
        inputVars:
          storage_class: {{ .STORAGE_CLASS }}
      - objectTemplate: templates/stateful/statefulset.yaml
        replicas: 1
        inputVars:
          Image_logging: '{{or .REGISTRY "quay.io/test_images"}}/logging:latest'
          Image_stressng: '{{ or .REGISTRY "quay.io/rh_ee_apalanis" }}/fedora-stress-ng'
          volumes:
            - name: pvc-1
              type: persistentVolumeClaim
              path: /var/vol

      {{- if .NETWORKS  }}
      - objectTemplate: templates/sriov_dpdk/serviceaccount.yaml
        replicas: 1
      - objectTemplate: templates/sriov_dpdk/deployment.yaml
        replicas: 1
        inputVars:
          Image_dpdk: '{{or .REGISTRY "registry.redhat.io/openshift4"}}/dpdk-base-rhel8:v4.8.0-8.1628601733'
          volumes:
            - name: pvc-1
              type: persistentVolumeClaim
              path: /var/vol
          networks: {{ .NETWORKS }}
          accelerator_model: {{ .ACCELERATOR_MODEL }}
          scc_privileged: true
      {{- end }}
