apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpdk-deployment-{{ .Replica }}
  labels:
    app: dpdk-deployment-{{ .Replica }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dpdk-deployment-{{ .Replica }}
  template:
    metadata:
      labels:
        app: dpdk-deployment-{{ .Replica }}
      annotations:
        {{- if .scc_privileged }}
        openshift.io/required-scc: privileged
        {{- end }}
        cpu-load-balancing.crio.io: disable
        cpu-quota.crio.io: disable
        irq-load-balancing.crio.io: disable
        {{- template "parts_network_defs" (dict "networks" .networks "indent" 8) }}
    spec:
      shareProcessNamespace: true
      serviceAccountName: sriovdpdksa
      runtimeClassName: {{ .performanceProfile | default "performance-openshift-node-performance-profile" }}
      containers:
        - image: {{ .Image_dpdk }}
          command:
            - /bin/sh
            - -c
            - |
              tail -f /dev/null | testpmd --socket-mem 2048,0 -n 4 --proc-type auto -l 2,3,4 --main-lcore=2 --file-prefix testpmd -a $PCIDEVICE_OPENSHIFT_IO_PCI_SRIOV_NET_{{ upper (index .Values.testpmd_interfaces 0) }} -a $PCIDEVICE_OPENSHIFT_IO_PCI_SRIOV_NET_{{ upper (index .Values.testpmd_interfaces 1) }} -- --nb-cores=2 --nb-ports=2 --rxq=1 --txq=1 --rxd=2048 --txd=2048 --forward-mode=mac --eth-peer=0,{{ .Values.edu_sriov_networks.llscu1.peer }} --eth-peer=1,{{ .Values.edu_sriov_networks.llscu2.peer }} --auto-start 2>&1 &
              sleep infinity
          imagePullPolicy: {{ .imagePullPolicy | default "Always" }}
          livenessProbe:
            exec:
              command:
                - ls
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 7
          name: dpdk-1
          resources:
            {{- $cpu_limit := .cpu_limit | default "16" }}
            {{- $mem_limit := .mem_limit | default "32Gi" }}
            {{- $hugepages_limit := .hugepages_limit | default | default "16Gi" }}
            requests:
              cpu: {{ (.cpu_request | default $cpu_limit) | quote }}
              memory: {{ (.mem_request | default $mem_limit) | quote }}
              hugepages-1Gi: {{ .hugepages_request | default $hugepages_limit | quote }}
              {{- if (.ephemeral_storage_request | default .ephemeral_storage_limit) }}
              ephemeral-storage: {{ (.ephemeral_storage_request | default .ephemeral_storage_limit) | quote }}
              {{- end }}
              {{- range $net := .networks }}
              {{ print ($net.resource | quote) ": '1'" }}
              {{- end }}
              {{- if .accelerator_model }}
              {{ print (.accelerator_model | quote) ": '1'" }}
              {{- end }}
            limits:
              cpu: {{ $cpu_limit | quote }}
              memory: {{ $mem_limit | quote }}
              hugepages-1Gi: {{ $hugepages_limit | quote }}
              {{- if .ephemeral_storage_limit }}
              ephemeral-storage: {{ .ephemeral_storage_limit | quote }}
              {{- end }}
              {{- range $net :=.networks }}
              {{ print ($net.resource | quote) ": '1'" }}
              {{- end }}
              {{- if .accelerator_model }}
              {{ print (.accelerator_model | quote) ": '1'" }}
              {{- end }}
          securityContext:
            privileged: true
            capabilities:
              add:
                - IPC_LOCK
                - NET_ADMIN
                - NET_BIND_SERVICE
                - SYS_NICE
                - NET_RAW
              drop:
                - ALL
            runAsUser: 0
          volumeMounts:
            - mountPath: /dev/hugepages
              name: hugepage
            {{ template "parts_volume_mounts" (dict "volumes" .volumes "indent" 12) }}
        {{- template "parts_extra_containers" (dict "N_extra_containers" (.N_extra_containers | default 0) "Image_ubi" (.Image_ubi | default "") "Replica" $suffix "extra_volumes" .extra_volumes "indent" 8 ) }}
      volumes:
        - emptyDir: {}
          name: shared-sockets
        - emptyDir:
            medium: HugePages
          name: hugepage
        {{- template "parts_volume_defs" (dict "volumes" .volumes "indent" 8) }}
