{{ $Replica := "1"}}
{{ if ne (index . "Replica") nil }}
{{ $Replica = .Replica }} {{/* Replica isn't set if replica set to 1  // TODO raise bug in kube-burner */}}
{{- end }}
{{ $suffix := $Replica }}
{{- if .group }}
{{- $suffix = print .group "-" $Replica }}
{{- end }}
kind: Service
apiVersion: v1
metadata:
  name: webserver-{{ $suffix }}
spec:
  selector:
    name: webserver-{{ $suffix }}
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
