{{ $Replica := "1"}}
{{ if ne (index . "Replica") nil }}
{{ $Replica = .Replica }} {{/* Replica isn't set if replica set to 1  // TODO raise bug in kube-burner */}}
{{- end }}
{{ $suffix := $Replica }}
{{- if .group }}
{{- $suffix = print .group "-" $Replica }}
{{- end }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-{{ $suffix }}
spec:
  capacity:
    storage: {{ .size | default "1Gi" }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: {{ .storage_class | default "general" }}
  hostPath:
    path: "/mnt/data"
