kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    {{- if .group }}
    name: pvc-{{ .group }}-{{ .Replica }}
    {{- else }}
    name: pvc-{{ .Replica }}
    {{- end }}
spec:
    accessModes:
        - ReadWriteOnce
    volumeMode: Filesystem
    resources:
        requests:
            storage: {{ .size | default "100Mi" }}
    storageClassName: {{ .storage_class | default "general" }}
