apiVersion: v1
kind: Secret
metadata:
{{- if .group }}
  name: secret-{{ .group }}-{{ .Replica }}
  {{- else }}
  name: secret-{{ .Replica }}
  {{- end }}
type: Opaque
{{- if .data }}
data: {{ mustToJson .data }}
{{- else }}
data:
  password: Zm9vb29vb29vb29vb29vbwo=
{{- end }}
