{{ $Replica := "1"}}
{{ if ne (index . "Replica") nil }}
{{ $Replica = .Replica }} {{/* Replica isn't set if replica set to 1  // TODO raise bug in kube-burner */}}
{{- end }}
{{ $suffix := $Replica }}
{{- if .group }}
{{- $suffix = print .group "-" $Replica }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: secret-{{ $suffix }}
type: Opaque
{{- if .data }}
data: {{ mustToJson .data }}
{{- else }}
data:
  password: Zm9vb29vb29vb29vb29vbwo=
{{- end }}
