{{ $Replica := "1"}}
{{ if ne (index . "Replica") nil }}
{{ $Replica = .Replica }} {{/* Replica isn't set if replica set to 1  // TODO raise bug in kube-burner */}}
{{- end }}
{{ $suffix := $Replica }}
{{- if .group }}
{{- $suffix = print .group "-" $Replica }}
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-{{ $suffix }}
  labels:
    group: load
    svc: stress-{{ $suffix }}
spec:
  replicas: {{ .num_of_replicas | default 1 | int }}
  selector:
    matchLabels:
      name: stress-{{ $suffix }}
  template:
    metadata:
      labels:
        group: load
        name: stress-{{ $suffix }}
      {{- if .networks }}
      annotations:
        {{- template "parts_network_defs" (dict "networks" .networks "indent" 8) }}
      {{- end }}
    spec:
      runtimeClassName: {{ .performanceProfile | default "performance-openshift-node-performance-profile" }}
      containers:
        - image: {{ .Image_stressng | quote }}
          imagePullPolicy: IfNotPresent
          name: stress-{{ $Replica }}
          args: ["sleep", "inf"]
          # Request and Limits must be identical for the Pod to be assigned to the QoS Guarantee
          resources:
            {{- $cpu_limit := .cpu_limit | default "50m" }}
            {{- $mem_limit := .mem_limit | default "150Mi" }}
            {{- $cpu_request := .cpu_request | default "40m" }}
            {{- $mem_request := .mem_request | default "100Mi" }}
            requests:
              cpu: {{ (.cpu_request | default $cpu_request) | quote }}
              memory: {{ (.mem_request | default $mem_request) | quote }}
              {{- if .hugepages_request | default .hugepages_limit }}
              hugepages-1Gi: {{ .hugepages_request | default .hugepages_limit | quote }}
              {{- end }}
              {{- if (.ephemeral_storage_request | default .ephemeral_storage_limit) }}
              ephemeral-storage: {{ (.ephemeral_storage_request | default .ephemeral_storage_limit) | quote }}
              {{- end }}
              {{- template "parts_network_resources" (dict "networks" .networks "indent" 14) }}
            limits:
              cpu: {{ $cpu_limit | quote }}
              memory: {{ $mem_limit | quote }}
              {{- if .hugepages_limit }}
              hugepages-1Gi: {{ .hugepages_limit | quote }}
              {{- end }}
              {{- if .ephemeral_storage_limit }}
              ephemeral-storage: {{ .ephemeral_storage_limit | quote }}
              {{- end }}
              {{- template "parts_network_resources" (dict "networks" .networks "indent" 14) }}
          env: {{- if .env }}{{ .env | toJson }}
            {{- else }}
            - name: stress_cpu
              value: {{ (.cpu_stress | default "2") | quote }}
            - name: stress_vm
              value: {{ (.vm_stress | default "1") | quote }}
            - name: stress_vm-bytes
              value: {{ (.vm_stress_bytes | default "50M") | quote }}
            {{- end }}
          {{- if or (gt ((append (.volumes | default list) (.extra_volumes | default list)) | len) 0) .hugepages_limit }}
          volumeMounts: {{- template "parts_volume_mounts" (dict "volumes" .volumes "indent" 12) }}
            {{- if .hugepages_limit }}
            - name: hugepage
              mountPath: /hugepages
            {{- end }}
          {{- end }}
        {{- template "parts_extra_containers" (dict "N_extra_containers" (.N_extra_containers | default 0) "Image_ubi" (.Image_ubi | default "") "Replica" $suffix "extra_volumes" .extra_volumes "indent" 8) }}
      dnsPolicy: Default
      terminationGracePeriodSeconds: 1
      {{- if or (gt ((append (.volumes | default list) (.extra_volumes | default list)) | len) 0) .hugepages_limit }}
      volumes:
        {{- if or (gt (.volumes | default list| len) 0) .hugepages_limit }}
        {{- template "parts_volume_defs" (dict "volumes" .volumes "indent" 8) }}
        {{- end }}
        {{- range $i, $e := (.extra_volumes | default list) }}
        {{- template "parts_volume_defs" (dict "volumes" $e "indent" 8) }}
        {{- end }}
        {{- if .hugepages_limit }}
        - name: hugepage
          emptyDir:
            medium: HugePages
        {{- end }}
      {{- end }}
